settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: /Users/mj/go/src/github.com/dfang/qor-demo
  path: /Users/mj/go/src/github.com/dfang/qor-demo
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
- name: /Users/mj/go/src/github.com/dfang/qor-demo
  path: /Users/mj/go/src/github.com/dfang/qor-demo
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
