# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  # dockerID: $(dockerID)  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: $(dockerID)/$(Build.Repository.Name):$(Build.SourceBranchName)-$(git rev-parse --short HEAD)  # Replace with the name of the image you want to publish

steps:

# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# - script: echo "make sure you've defined docker credentials in env"
- script: docker login -u $(dockerID) -p $(dockerPWD)
  displayName: 'docker login'
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
- script: docker tag $(imageName) $(dockerID)/$(Build.Repository.Name):latest
  displayName: 'docker tag latest'
- script: docker push $(imageName)
  displayName: 'docker push'
- script: docker push $(dockerID)/$(Build.Repository.Name):latest
  displayName: 'docker push latest'
